# <TEMPLATED FILE!>
# This file comes from the templates at https://github.com/chmeliik/task-repo-boilerplate.
# Please consider sending a PR upstream instead of editing the file directly.

name: Validate PR - Trusted Artifact variants
'on':
  pull_request:
    branches: [main]
  merge_group:
    types: [checks_requested]
jobs:
  go:
    name: Check Trusted Artifact variants
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Check Trusted Artifact variants
        id: check
        run: hack/generate-ta-tasks.sh

      # TODO: re-enable this check
      # - name: Check missing Trusted Artifact variants
      #   id: missing
      #   run: hack/missing-ta-tasks.sh

      - name: Attach patch
        if: ${{ steps.check.conclusion == 'failure' }}
        uses: actions/upload-artifact@v4
        with:
          name: Trusted artifacts patch
          path: ./ta.patch
